# Generated by Django 5.2 on 2025-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_huesped_fecha_nacimiento_huesped_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='documento_tipo',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte')], max_length=30, null=True),
        ),
    ]
