# Generated by Django 5.2 on 2025-09-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_huesped_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='documento_tipo',
            field=models.CharField(choices=[('DNI', 'DNI / rut'), ('PASAPORTE', 'Pasaporte')], max_length=30, null=True),
        ),
    ]
