# Generated by Django 5.2 on 2025-09-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_huesped_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
