# Generated by Django 5.2 on 2025-09-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_huesped_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
