# Generated by Django 5.2 on 2025-10-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_alter_huesped_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='capacidad',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='equipamiento',
            field=models.TextField(blank=True, help_text='Lista de equipamiento separado por comas', null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones/'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='categoria',
            field=models.CharField(choices=[('Turista', 'Turista'), ('Premium', 'Premium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento'), ('Reservada', 'Reservada')], default='Disponible', max_length=30),
        ),
    ]
