# Generated by Django 5.2 on 2025-10-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_habitacion_capacidad_habitacion_equipamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Reservada', 'Reservada')], default='Disponible', max_length=30),
        ),
    ]
